### ISSUE TITLE
For Restoring Comboboxes

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#20]
Maybe we already discussed this, but when saving why don't we just store the full contents of the combobox and the item selected so that when restoring, we don't have to do anything fancy, we just populate the full combobox list? Seems like that might simplify things.

**Comment by tisaconundrum2** [comment]
http://stackoverflow.com/questions/4529815/saving-an-object-data-persistence

**Comment by tisaconundrum2** [comment]
The following PyQt5 classes may be pickled.
http://pyqt.sourceforge.net/Docs/PyQt5/pickle.html

- QByteArray
- QColor
- QDate
- QDateTime
- QKeySequence
- QLine
- QLineF
- QPoint
- QPointF
- QPolygon
- QRect
- QRectF
- QSize
- QSizeF
- QTime

we might not be able to pickle entire objects.

**Comment by ryanbanderson** [comment]
According to that previous stackoverflow link, it looks like the "dill" library might help if pure pickle can't do it.

**Comment by tisaconundrum2** [comment]
The reason we can't view **everything** (all the contents) inside a given UI is because there are some things that are made private within the class. This means that we **have to use a function** to view it.

For example `self.color_choices` is an object from the class QComboBox
but we want to see the given items inside this QComboBox, however we can't because the contents of the items that are inside the comboBox are made private. If we want to see a single item we can, but it can only be done using a function. In this case we use this `self.color_choices.itemText(0)`

`self.color_choices` is the QComboBox object
`itemText()` is the QComboBox function that calls particular private variables from within the object.

In a nut-shell this means we can't `dill` or `pickle` an entire UI because there are private variables that `dill` or `pickle` will ___never___ be able to see.

**Comment by tisaconundrum2** [comment]
To solve this problem, I'll be using Qtickle, which is library built to "scan" the UI and use their dedicated functions to mine information from the UI
